### ISSUE TITLE
How to do a comment in c++

### ISSUE THREAD

**Issue by adelatorresaavedra** [adelatorresaavedra/C_plus_plus_For_Beginners#2]
Do a markdown with types of comments in c++

**Comment by farhansyed2626** [comment]
For Single Line Comment - Just Put // in front of a line to make the rest of the line commented
For Multiple Line Comment - Put /* before the text to mark the beginning of comment , and add /* after the ending of your text to make it commented.

**Comment by Jovalga** [comment]
ok, I'll do the markdown file ;)
